FROM mcr.microsoft.com/dotnet/sdk:7.0

RUN apt-get update \
&& apt-get install -y zsh \
&& sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended