version: "3.8"

services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
      volumes:
         - ..:/workspace:cached
      command: sleep infinity
      network_mode: service:db
      depends_on:
         - db
         - rabbitmq

   db:
      image: postgres
      restart: unless-stopped
      ports:
         - "5432"
      environment:
         POSTGRES_PASSWORD: demo
         POSTGRES_USER: demo
         POSTGRES_DB: demo

   rabbitmq:
      image: rabbitmq:3-management
      ports:
         - "5672"
         - "15672"
      environment:
         - RABBITMQ_DEFAULT_USER=demo
         - RABBITMQ_DEFAULT_PASS=demo
      restart: unless-stopped
